version: '3.8'
services:
  db:
    build: .
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "ListaDeTarefas"
      MYSQL_USER: "usuario"
      MYSQL_PASSWORD: "root"
    ports:
      - "3307:3306"
